### ISSUE TITLE
AI_TypeValidationError when using both schema and stream

### ISSUE THREAD

**Issue by maiconcarraro** [AmAzing129/use-ai-lib#30]
I was exploring this demo https://try-chromeai.vercel.app/smart-form and the form wasn't working, and checking the source code: https://github.com/jeasonstudio/chrome-ai/blob/85f78151ebe95ace68b2843f0cc0b787f923c84f/app/smart-form/page.tsx#L81-L89

It's using both stream and schema together, If I remove the `stream: true` to use directly the [`useGenerateObject`](https://github.com/AmAzing129/use-ai-lib/blob/f3a958d24d5bd6a46d6e4c7d3bec4bc95aa957aa/src/queries/useGenerateObject.tsx#L58) then everything **works correctly**.

But using the original code with **stream true**, it returns an error from the hook:
```
AI_TypeValidationError: Type validation failed: Value: undefined.
Error message: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
    at _TypeValidationError.wrap (index.mjs:483:86)
    at safeValidateTypes (index.mjs:252:80)
    at Object.validateFinalResult (index.mjs:1513:85)
    at Object.transform (index.mjs:2379:55)
```

Payloads are the same, I didn't see an example in your readme using both together, let me know if you need more information.

**Comment by webbrain-one** [comment]
Thanks for reporting this! I've opened [PR #44](https://github.com/AmAzing129/use-ai-lib/pull/44) to address the `AI_TypeValidationError` that occurs when using `stream: true` alongside a schema. The fix ensures that streamed responses are properly handled and validated against the expected type, preventing the `undefined` value error you encountered.

Let me know if you have any questions or run into any other issues. Appreciate the detailed report! 🙌
